name: my_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_secure_storage: ^9.0.0
  cloud_firestore: ^5.6.1
  firebase_database: ^11.2.0
  firebase_core: ^3.9.0
  firebase_auth: ^5.4.0
  image_picker: ^0.8.7+3
  http_parser: ^4.0.0
  intl: ^0.19.0
  loading_animation_widget:
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.2 # Ensure it's the latest version
  file_picker: ^6.0.0
  path_provider: ^2.1.2
  google_fonts: ^6.1.0
  
  material_symbols_icons: ^4.2811.0
  # agora_rtc_engine: ^6.5.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  dots_indicator: ^3.0.0
  indexed: ^0.0.8
  flutter_quill: ^10.8.5
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1
  flutter_webrtc: ^0.12.7
  uuid: ^4.0.0
  audioplayers: ^6.1.1
  video_player: ^2.9.2
  video_player_web: ^2.3.4
  chewie: ^1.7.4
  mime: ^2.0.0
  url_launcher: ^6.3.1
  razorpay_flutter: ^1.4.0
  permission_handler: ^11.4.0
  share_plus: ^10.1.4 # or latest version
  youtube_player_flutter: ^9.1.1 
  flutter_flip_card: ^0.0.6
  webview_flutter: ^4.10.0

dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  video_player_web: ^2.0.19 # Add this for Web support

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/default-pic.jpg
    - assets/images/
    - assets/images/no_results.png
    - assets/images/c1.png
    - assets/sounds/ringtone.mp3
    - assets/data/
    - assets/data/top_trending_events.json
    - assets/data/updated_college_ranking.json
    - assets/data/colleges/college_ranking.json
    - assets/images/homepage/trending_exams/
    - assets/images/homepage/trending_colleges/
    - assets/images/homepage/trending_events/
    - assets/images/homepage/trending_exams/exams_page/Medical/
    - assets/images/homepage/trending_exams/exams_page/Engineering/
    - assets/images/homepage/trending_exams/exams_page/Law/
    - assets/images/homepage/trending_exams/exams_page/Management/
    - assets/images/homepage/trending_exams/exams_page/Architecture/
    - assets/data/exams/engineering_exams.json
    - assets/data/exams/medical_exams.json
    - assets/data/exams/law_exams.json
    - assets/data/exams/management_exams.json
    - assets/data/exams/architecture_exams.json
    - assets/data/exams/exam_info.json
    - assets/data/courses/trending-courses.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
